author:
  avatar : "profile.png"
  name   : "Emanuele Fedeli"
  pronouns:
  bio    : "Postdoctoral Researcher in Sociology and Quantitative Methods"
  location: "Milan, Italy"
  employer: "University of Milan"
  uri    :
  email  : "nome.cognome@unimi.it"

  # Academic websites
  academia         :
  arxiv            :
  googlescholar    : "https://scholar.google.com/citations?user=pS_XDH4AAAAJ&hl=it"
  inspire-hep      :
  impactstory      :
  orcid            :
  semantic         :
  ssrn             :
  pubmed           :
  researchgate     :
  scopus           :
  zotero           :

  # Repositories and software development
  bitbucket        :
  codepen          :
  dribbble         :
  github           : "emanuelefedeli"
  kaggle           :
  stackoverflow    :

  # Social media
  artstation       :
  bluesky          : "fedeli88.bsky.social"
  facebook         :
  flickr           :
  foursquare       :
  goodreads        :
  google_plus      :
  keybase          :
  instagram        :
  lastfm           :
  linkedin         :
  mastodon         :
  medium           :
  pinterest        :
  soundcloud       :
  steam            :
  telegram         :
  tumblr           :
  twitter          :
  vine             :
  weibo            :
  wikipedia        :
  xing             :
  youtube          :
  zhihu            :
